import {StyleSheet} from 'react-native';
import { colors} from '../../../theme/Colors';

const styles = StyleSheet.create({
  cardContainer: {
    height: 137,
    width: '100%',
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 15,
    position: 'relative',
    borderColor:"#272058",
    borderWidth: 1,
    backgroundColor: '#170F4B',
  },
  cardContainerTwo: {
    height: 137,
    width: '100%',
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 15,
    position: 'relative',
    borderColor:"#272058",
    borderWidth: 1,
    backgroundColor: '#170F4B',
  },
  matchImage: {
    height: 111 - 35,
    width: '100%',
  },
  notifiedIcon: {
    height: 16,
    width: 16,
    position: 'absolute',
    right: 10,
    top: 5,
  },
  seriesNametext: {
    position: 'absolute',
    paddingHorizontal: 15,
    top: 30,
  },
  linerLine: {
    height: 0.7,
    width: '95%',
    alignSelf: 'center',
    top: 30,
  },
  teamShortNameText: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
  },
  teamShortNameTextTwo: {
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  bottom: {
    backgroundColor: '#ffffff09',
    paddingHorizontal: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 15,
  },
  teamContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: '100%',
    paddingHorizontal: 15,
    marginTop: 20,
    width: '100%',
  },
  teamImage: {
    height: 40,
    width: 40,
    borderRadius:20,
    resizeMode: 'contain',
  },
  textStyle: {
    fontSize: 11,
    marginTop: -1,
  },
  teamName: {
    lineHeight: 15,
    marginTop: 15,
  },
  timeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  lineUpOut: {
    alignSelf: 'flex-end',
    marginRight: -16,
    marginTop: -10,
  },
  greenCircle: {
    height: 8,
    width: 8,
    backgroundColor: colors.green,
    marginRight: 5,
    borderRadius: 50,
    marginTop: 7,
  },
  contestName: {
    // width: 'auto',
    // minWidth: 38,
    borderWidth: 1,
    borderColor: '#3EAA35',
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 6,
    flexDirection: 'row',
    // marginBottom: 5,
    width: 129,
    height: 21,
  },
  contestNameTwo: {
    borderWidth: 1,
    borderColor: '#5F338B15',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  teamShortName: {
    fontSize: 12,
    color: 'white',
  },
  completeView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dotView: {
    height: 8,
    width: 8,
    marginRight: 5,
    borderRadius: 100,
    backgroundColor: colors.green,
  },
  teamConunt: {
    flexDirection: 'row',
    alignItems: 'center',
  },
});

export default styles;
